---
title: "trial2022/09/03"
author: "Su Qing"
date: "2022/9/3"
output: html_document
---

```{r setup, message=FALSE}
knitr::opts_chunk$set(eval = FALSE)
library(tidyverse)
library(DT)
library(palmerpenguins)
library(dplyr)
library(here)
here()
```

## separate函数

```{r}
tb <- tibble::tribble(
  ~day, ~price,
  1,   "30-45",
  2,   "40-95",
  3,   "89-65",
  4,   "45-63",
  5,   "52-42"
)
tb
tb %>% 
  separate(price, into = c("low", "high"), sep = "-")
```

## unit函数

```{r}
df <- expand_grid(id=c(1,2),x = c("a", NA), y = c("b", NA))
df
df %>% 
  unite(col="xy",c(x,y),sep = "_",remove = FALSE,na.rm = TRUE)

```

## distinct函数

```{r}
df <- tibble::tribble(
  ~x, ~y, ~z,
  1, 1, 1,
  1, 1, 2,
  1, 1, 1,
  2, 1, 2,
  2, 2, 3,
  3, 3, 1
)
df
df %>%
  distinct(x, y, .keep_all = TRUE) # 只保留最先出现的row
```

## 创建克隆变量

```{r}
df <- tibble(id=c(1,1,2,2,3,3,4,4,5,5),year=rep(c(2015,2018),times=5),depr=c(2,NA,NA,2,4,NA,8,3,7,NA),sati=c(NA,4,NA,8,9,NA,7,3,7,NA))
df %>% 
  mutate(across(everything(),.x=.x,.names = "{.col}_a"))
```

## 
